apiVersion: v1
kind: Service
metadata:
#  name: {{ include "koko.fullname" . }}
  name: koko
  labels:
    {{- include "koko.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.koko.port }}
      targetPort: koko
      nodePort: {{ .Values.service.koko.nodePort }}
      protocol: TCP
      name: koko
    - port: {{ .Values.service.koko5000.port }}
      targetPort: koko5000
      protocol: TCP
      name: koko5000
  selector:
    {{- include "koko.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
