apiVersion: v1
kind: Service
metadata:
#  name: {{ include "nginx.fullname" . }}
  name: nginx
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: nginx
      protocol: TCP
      name: nginx
      nodePort: {{ .Values.service.nodeport }}

  selector:
    {{- include "nginx.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
