apiVersion: v1
kind: Service
metadata:
#  name: {{ include "mysql.fullname" . }}
  name: mysql
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql  # http
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP